### PR TITLE
(feat) add support for private keys

### LINKED ISSUE #5: private key support (ES256)
Would you consider accepting an ES256 JWK as input and returning a PEM private key? The format I'm thinking of for the jwk would be:

    {
        alg: 'ES256',
        crv: 'P-256',
        kty: 'EC',
        d: 'base64url-encoded-private-key-d-value-blah'
    }

### PR DESCRIPTION
**Pull request by omsmith**
Closes #5 

Just opening this up early so people can track progress

- [x] Accept private option
- [x] Accept private ec keys
- [x] Don't require x/y for ec private keys
- [x] Accept private rsa keys
- [x] Everything is tested swell-like
- [x] Update README

### CODE REVIEW

**Comment by omsmith** [comment]
@focusaurus @jbdatko this work for you?

@jopnick @j3parker Once-over?

**Comment by focusaurus** [comment]
Looks OK to me for converting private jwk to private pem. 

What's the use case for private jwk to public pem? Seems like that could cause confusion and make it likely for a developer to accidentally leak a private key. Maybe throwing an error in that case would be better?

**Comment by jbdatko** [comment]
@focusaurus If you have a private EC key for example, you can extract (derive) the public key portion. So I think private-jwk-to-public-pem is useful in the case I generate a private key and need the OpenSSL compatible public portion. Also, sometimes one may not want to store the private+public keys if the public can be re-derived.

It's a convenience feature, but a nice one, IMHO.

**Comment by jbdatko** [comment]
@omsmith Thanks, looks good.

**Comment by focusaurus** [comment]
Ah that makes sense now. Thanks.

**Pull request merged**
